version: '3.3'
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '8000:80'
            - '8001:443'
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        environment:
            - PORT=5000
        volumes:
            - /app/node_modules
            - ./server/src:/app/src
